### ISSUE TITLE
[Deprecation] CSS cannot be loaded from file: URLs unless they end in a .css file extension.

### ISSUE THREAD

**Issue by justintaddei** [electron-userland/electron-compile#314] opened 2018-10-22 01:35 UTC
Updating to the latest version of Electron (3.0.5) seems to break electron-compile.

Styles are no longer loaded and the dev tools console displays this warning:
[Deprecation] CSS cannot be loaded from file: URLs unless they end in a .css file extension.

Obviusly this is because the <head> of my app contains:
<link rel="stylesheet" href="path/to/styles.scss">

How do I overcome this and still use electron-forge?

**Comment by malept** [comment] 2019-01-02 23:19
Duplicate of #315.

**Closed by malept** 2019-01-02 23:19 UTC
